Repository peer-42seoul/peer-noti, pull requests merged in 2023-05, with the labels that each got.

#3 [docs] Add templates
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitmessage
Labels: 📄 documentation

#5 [feat] Setup Django dev env
  .gitignore
  peer-noti/config/__init__.py
  peer-noti/config/asgi.py
  peer-noti/config/settings.py
  peer-noti/config/urls.py
  peer-noti/config/wsgi.py
  peer-noti/manage.py
  peer-noti/slackbot/__init__.py
  peer-noti/slackbot/admin.py
  peer-noti/slackbot/apps.py
  peer-noti/slackbot/migrations/__init__.py
  peer-noti/slackbot/models.py
  peer-noti/slackbot/tests.py
  peer-noti/slackbot/urls.py
  peer-noti/slackbot/views.py
  peer-noti/static/bootstrap.min.css
  peer-noti/static/bootstrap.min.js
  peer-noti/templates/base.html
  requirements.txt
Labels: 📄 documentation, 💻 feature

#8 [docs] Update readme
  README.md
Labels: 📄 documentation

#7 [feat] Send DM with SlackBot
  peer-noti/config/settings.py
  peer-noti/slackbot/slack_api.py
  peer-noti/slackbot/urls.py
  peer-noti/slackbot/views.py
Labels: 💻 feature

#10 [feat] Create demo web page for send DM
  peer-noti/config/settings.py
  peer-noti/slackbot/forms.py
  peer-noti/slackbot/slack_api.py
  peer-noti/slackbot/views.py
  peer-noti/templates/alert_message.html
  peer-noti/templates/form_errors.html
  peer-noti/templates/slackbot/dm_form.html
  peer-noti/templates/slackbot/index.html
Labels: 🐞 bug, 💻 feature, 🛠 refactoring
